##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-icon-theme
    - autopoint
    - curl
    - git
    - icon-naming-utils
    - intltool
    - librsvg2-bin
    - make
    - pkg-config

before_scripts:
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - mkdir html-report
  - NOCONFIGURE=1 ./autogen.sh
  - ./configure --enable-compile-warnings=maximum
  - make
  - make check
  - make install

after_scripts:
  - make distcheck
