##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-icon-theme
    - autopoint
    - curl
    - clang-tools
    - expect #required for unbuffer
    - git
    - intltool
    - librsvg2-bin
    - libxml-simple-perl #required for ctk-icon-naming-utils
    - make
    - pkg-config

before_scripts:
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/ctk-icon-naming-utils master

build_scripts:
  - ./make-scanbuild
