##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-icon-theme
    - autopoint
    - curl
    - git
    - icon-naming-utils
    - intltool
    - librsvg2-bin
    - make
    - pkg-config

before_scripts:
  # Install cafe-common from master branch
  - if [ ! -e cafe-common-master ]; then
  -     cd ${START_DIR}
  -     git clone --depth 1  https://github.com/cafe-desktop/cafe-common.git -b master cafe-common-master
  -     cd cafe-common-master
  -     ./autogen.sh
  -     if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -         ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  -     else
  -         ./configure --prefix=/usr
  -     fi
  -     make
  -     make install
  - fi

after_scripts:
#  - make distcheck
